application: nseversion1
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /style
  static_dir: style

- url: /images
  static_dir: images

- url: .*
  script: main.app

- url: /_ah/login_required
  script: do_openid_login.app
  
libraries:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest

builtins:
- deferred: on